- name: Setup Node.js with MongoDB on Remote Host
  hosts: 43.205.191.103
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name: ['nodejs', 'npm']
        state: present

    - name: Clone app repository
      git:
        repo: https://github.com/arhantbararia/node_app.git
        dest: /home/ec2-user/nod_app

    - name: Install app dependencies
      command: npm install express mongodb
      args:
        chdir: /home/ec2-user/node_app

    - name: Start the node app
      command: node app.js
      args:
        chdir: /home/ec2-user/nod_app



